databases:
  - name: odin_facebook
    databaseName: odin_facebook
    user: odin_facebook

services:
  - type: web
    name: odin-facebook
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: odin_facebook
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false